question_data = [
    {
        "category": "Science & Nature", 
        "type": "boolean", 
        "difficulty": "medium",
        "text": "The Neanderthals were a direct ancestor of modern humans.",
        "answer": "False"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "text": "Igneous rocks are formed by excessive heat and pressure.",
     "answer": "False"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "A person can get sunburned on a cloudy day.", "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "The Doppler effect applies to light.", "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
     "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "The planet Mars has two moons orbiting it.", "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "Steel is an alloy of Iron and Carbon.", "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
     "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
     "answer": "False"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "Shrimp can swim backwards.", "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "Type 1 diabetes is a result of the liver working improperly.",
     "answer": "False"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "text": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
     "answer": "True"},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "text": "Salt is 100% composed of Sodium.", "answer": "False",
},
    ]

    # this is a list containing dictionaries which can be recognised by the dictionary key
# science and nature question

# [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with "
#              "your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled"
#              " to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]


# [
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "The HTML5 standard was published in 2014.", "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "The first computer bug was formed by faulty wires.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "Linus Torvalds created Linux and Git.", "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "The logo for Snapchat is a Bell.", "answer": "False",},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "RAM stands for Random Access Memory.", "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "Ada Lovelace is often considered the first computer programmer.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "MacOS is based on Linux.", "answer": "False",},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "The open source program Redis is a relational database server.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
#     "text": "DHCP stands for Dynamic Host Configuration Port.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "&quot;HTML&quot; stands for Hypertext Markup Language.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
#     "text": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "Time on Computers is measured via the EPOX System.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "The Windows ME operating system was released in the year 2000.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#     "text": "Linux was first created as an alternative to Windows XP.",
#     "answer": "False"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "Android versions are named in alphabetical order.",
#     "answer": "True"},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#     "text": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
#     "answer": "False"}]
  
  
#     [
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
#     "answer": "False"},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "An octopus can fit through any hole larger than its beak.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "A slug&rsquo;s blood is green.", "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "Kangaroos keep food in their pouches next to their children.",
#     "answer": "False"},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "A bear does NOT defecate during hibernation. ",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "The average lifespan of a wildcat is only around 5-6 years. ",
#     "answer": "False"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "Rabbits are rodents.", "answer": "False",},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "The Platypus is a mammal.", "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "A caterpillar has more muscles than humans do.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "Cats have whiskers under their legs.", "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "The Killer Whale is considered a type of dolphin.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "Tigers have one colour of skin despite the stripey fur.",
#     "answer": "False"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "Rabbits can see what&#039;s behind themselves without turning their heads.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "medium",
#     "text": "You can tell the age of a ladybird by counting the spots on his back.",
#     "answer": "False"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "Rabbits are carnivores.", "answer": "False",},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "The internet browser Firefox is named after the Red Panda.",
#     "answer": "True"},
#     {"category": "Animals", "type": "boolean", "difficulty": "easy",
#     "text": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
#     "answer": "True"}
    
#     ]
